/content/documents/myproject/service:
  jcr:primaryType: hippostd:folder
  jcr:mixinTypes: ['hippotranslation:translated', 'mix:versionable']
  jcr:uuid: 3f907004-66ce-4d6f-b04d-dc06b1c19c69
  hippostd:foldertype: [new-translated-folder, new-document]
  hippotranslation:id: 441d3f5f-b58e-459a-8225-50c26d04f8b2
  hippotranslation:locale: en
  /about-us:
    jcr:primaryType: hippo:handle
    jcr:mixinTypes: ['hippo:named', 'hippo:versionInfo', 'mix:referenceable']
    jcr:uuid: a570691d-119a-418d-9e66-2cdf887f40aa
    hippo:name: About Us
    hippo:versionHistory: d394c7f0-c302-442c-807c-03e46502879a
    /about-us[1]:
      jcr:primaryType: myproject:contentdocument
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: b92366c0-7189-4dba-9494-83330bc86fa4
      hippo:availability: []
      hippo:related___pathreference: []
      hippostd:state: draft
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-06-07T13:24:03.459-04:00
      hippostdpubwf:lastModificationDate: 2019-06-07T13:24:03.459-04:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 325d6cd6-f7ea-426c-a64b-e7fc15c198ea
      hippotranslation:locale: en
      myproject:introduction: About Us Introduction Text
      myproject:publicationdate: 0001-01-01T13:00:00+01:00
      myproject:title: About Us
      /myproject:content:
        jcr:primaryType: hippostd:html
        hippostd:content: <h4>About Us Content Rich Text!!</h4>
    /about-us[2]:
      jcr:primaryType: myproject:contentdocument
      jcr:mixinTypes: ['mix:referenceable', 'mix:versionable']
      jcr:uuid: f383c60c-e230-46b3-b366-584a42645a4f
      hippo:availability: [preview]
      hippo:related___pathreference: []
      hippostd:state: unpublished
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-06-07T13:24:03.459-04:00
      hippostdpubwf:lastModificationDate: 2019-06-07T13:24:42.875-04:00
      hippostdpubwf:lastModifiedBy: admin
      hippotranslation:id: 325d6cd6-f7ea-426c-a64b-e7fc15c198ea
      hippotranslation:locale: en
      myproject:introduction: About Us Introduction Text
      myproject:publicationdate: 0001-01-01T13:00:00+01:00
      myproject:title: About Us
      /myproject:content:
        jcr:primaryType: hippostd:html
        hippostd:content: <h4>About Us Content Rich Text!!</h4>
    /about-us[3]:
      jcr:primaryType: myproject:contentdocument
      jcr:mixinTypes: ['mix:referenceable']
      jcr:uuid: db83dd71-b9df-4f65-986b-f75992e2e9a0
      hippo:availability: [live]
      hippo:related___pathreference: []
      hippostd:state: published
      hippostdpubwf:createdBy: admin
      hippostdpubwf:creationDate: 2019-06-07T13:24:03.459-04:00
      hippostdpubwf:lastModificationDate: 2019-06-07T13:24:42.875-04:00
      hippostdpubwf:lastModifiedBy: admin
      hippostdpubwf:publicationDate: 2019-06-07T13:24:45.288-04:00
      hippotranslation:id: 325d6cd6-f7ea-426c-a64b-e7fc15c198ea
      hippotranslation:locale: en
      myproject:introduction: About Us Introduction Text
      myproject:publicationdate: 0001-01-01T13:00:00+01:00
      myproject:title: About Us
      /myproject:content:
        jcr:primaryType: hippostd:html
        hippostd:content: <h4>About Us Content Rich Text!!</h4>
